# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np 

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/vinit/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/vinit/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/vinit/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/vinit/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/vinit/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/vinit/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/vinit/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/vinit/anaconda3/include']
None


#### 3. Create a null vector of size 10

In [4]:
a = np.zeros((1,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 4.  How to find the memory size of any array

In [5]:
# Here I find size of a
print(a.size * a.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            ~/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `ou

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [8]:
a[0,4] = 1
print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


#### 7.  Create a vector with values ranging from 10 to 49

In [13]:
vec = np.arange(10,50,1)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [14]:
vec1 = vec[::-1]
print(vec1)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
mat = np.arange(9).reshape((3,3))
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [19]:
b = np.array([1,2,0,0,4,0])
print(np.nonzero(b)) # .nonzero() gives a array of indices of non zero elements

#Alternate code
print(np.where(b != 0)[0])


(array([0, 1, 4]),)
[0 1 4]


#### 11. Create a 3x3 identity matrix

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values

In [24]:
np.random.random((3,3,3))

array([[[0.95256992, 0.50042359, 0.32473532],
        [0.52102444, 0.9267615 , 0.77034694],
        [0.54904842, 0.95173181, 0.27783022]],

       [[0.29314857, 0.77576752, 0.5798047 ],
        [0.55376772, 0.32318121, 0.91196876],
        [0.15236571, 0.74500386, 0.59689567]],

       [[0.68387737, 0.60338467, 0.71560406],
        [0.00231061, 0.68521369, 0.81942781],
        [0.08901739, 0.61555474, 0.04516997]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [30]:
arr = np.random.random((10,10))
print(arr)
print("The max element is: ",arr.max())
print("The min element is: ",arr.min())

[[3.70299613e-02 5.45227481e-01 1.62013220e-01 5.47184943e-01
  8.53959871e-01 2.62400263e-01 6.33047804e-01 8.60152423e-01
  5.72039676e-01 5.71509126e-01]
 [6.57529572e-01 1.37548392e-01 6.62046739e-02 1.51219414e-01
  4.24343119e-01 9.31119293e-01 6.07798987e-01 2.10289062e-01
  6.42537107e-01 6.55256215e-01]
 [8.74616332e-01 3.19254827e-01 4.32641410e-01 3.05810650e-01
  6.73420919e-01 5.40128853e-01 4.99857528e-01 1.69346200e-01
  9.49539824e-01 2.99871929e-01]
 [6.43108423e-01 8.81885838e-01 9.25630917e-01 8.52150009e-01
  4.15564964e-01 1.97243652e-01 4.65700975e-01 1.94209779e-01
  7.25475217e-01 9.79986612e-01]
 [5.76288995e-01 5.91277953e-01 3.59272424e-01 9.45331376e-02
  2.33492318e-01 3.72699679e-01 5.08112844e-01 9.26626147e-02
  9.18853934e-01 9.51501777e-01]
 [2.03483846e-01 4.21446602e-02 5.26399540e-01 9.99535966e-01
  5.55354231e-02 6.46693764e-01 6.35178971e-01 8.40511102e-01
  9.68517296e-01 7.15831773e-01]
 [3.27975853e-01 2.35631216e-01 2.06872729e-01 9.28756373e

#### 14. Create a random vector of size 30 and find the mean value

In [33]:
arr2 = np.random.random(30)
print(arr2)
print("The mean is: ",arr2.mean())


[7.02035732e-01 4.19477781e-04 4.00980257e-01 1.01043375e-01
 3.91866963e-01 3.16426879e-01 5.89276699e-01 4.68331530e-01
 7.42789621e-01 6.29871232e-01 6.91676438e-01 6.23941240e-01
 3.16477089e-01 2.44807928e-02 2.59414324e-01 5.69428480e-01
 1.51309934e-01 2.58110161e-01 4.57682151e-01 7.06900932e-01
 1.70719443e-01 4.12674551e-01 1.91497074e-01 5.28972374e-01
 1.05682217e-01 9.01309405e-01 1.16831850e-01 6.96520879e-01
 4.14998467e-01 1.67607650e-01]
The mean is:  0.40364257393716924


#### 15. Create a 2d array with 1 on the border and 0 inside

In [42]:
n = int(input())
arr3 = np.zeros((n,n))
arr3[0,] = 1
arr3[:,0] = 1
arr3[n-1,] = 1
arr3[:,n-1] = 1
print(arr3)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [43]:
mat1 = np.zeros((5,5))
for i in range(1,5):
    mat1[i,i-1] = i
print(mat1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [50]:
check = np.zeros((8,8))
for i in range(8):
    check[i,i%2::2] = 1
print(check)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [55]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)
